### ISSUE TITLE
Bug: Background maps do not load correctly

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#146]
NSL terrain map & OSM do not load when zooming, cache issue?

**Comment by SannaJokela** [comment]
![chrome_TZhaO9Kp2Y](https://user-images.githubusercontent.com/23258285/161507790-99a88c27-0417-4149-aec6-ff34f4e354cc.gif)

Here is a gif what happens. When changing to another background layer, the vectors go crazy, ping @Rikuoja

**Comment by Rikuoja** [comment]
Console reports
```TypeError: undefined is not an object (evaluating 't.layout.get')```

at maplibre-gl.js

```
                this._sortAcrossTiles = "viewport-y" !== t.layout.get("symbol-z-order") && !t.layout.get("symbol-sort-
```

so this is some kind of a problem with maplibre. Will investigate.

**Comment by Rikuoja** [comment]
Nope. Actually happens

1) when selecting default style in the menu *again*,
2) first selecting another style, *then* selecting any other style.

Does not occur when selecting the same style again.

**Comment by Rikuoja** [comment]
Aha! This is an error in (some) of our map layers on top of the basic style.

When there are no symbol layers, only the base map style, this doesn't happen.

**Comment by Rikuoja** [comment]
Narrowing down the problem one layer at a time.

**Comment by Rikuoja** [comment]
Okay, so this happens if the OSM layers OR the stop layers are active.

So apparently a problem with layer styles with icons.

**Comment by Rikuoja** [comment]
But not a problem with basic layer styles with icons.

More specifically, this only happens when a symbol layer is *added* at render. When the same symbol layer is present in the base map style, it renders fine without crashing.

**Comment by Rikuoja** [comment]
Also, icons are missing in styles other than the basic style. We should load the icons so that they are present in all styles. Might have something to do with this bug?

**Comment by Rikuoja** [comment]
Aha! `styleDiffing={false}` prop to `MapGL` will fix this, so apparently this is a bug when diffing styles with missing images.

At style reload, the style will lose any images (they are only loaded on first load), and probably style diff crashes due to this.

So to make icons work in all styles, let's also add them here whenever the style changes.

**Comment by Rikuoja** [comment]
Could not reproduce the bug with maplibre and same library versions in https://codesandbox.io/s/misty-cache-12khjj?file=/src/index.js 

Perhaps the bug is a combination of style diffing with a style that is set dynamically in code? In tarmo, we cannot set the style file directly by style url, we first load the style JSON, then insert the correct api key, and then set the style asynchronously.

Perhaps this confuses the styleDiffing?
